FROM docker.io/fedora:22

RUN dnf install -y gcc
RUN dnf install -y autoconf automake libtool
RUN dnf install -y check
RUN dnf install -y check-devel
RUN dnf install -y dejagnu
RUN dnf install -y make
RUN dnf install -y git
