FROM docker.io/fedora:22

RUN dnf install -y gcc
RUN dnf install -y autoconf automake libtool
RUN dnf install -y check
RUN dnf install -y check-devel
RUN dnf install -y make
RUN dnf install -y git
RUN dnf install -y wget
RUN dnf install -y bzip2
RUN dnf install -y gzip
RUN dnf install -y tar
RUN dnf install -y unzip
RUN dnf install -y perl
RUN dnf install -y patch
RUN dnf install -y diffutils
RUN dnf install -y diffstat
RUN dnf install -y cpp
RUN dnf install -y gcc-c++
RUN dnf install -y texinfo
RUN dnf install -y chrpath
RUN dnf install -y ccache
RUN dnf install -y perl-Data-Dumper
RUN dnf install -y perl-Text-ParseWords
RUN dnf install -y perl-Thread-Queue
RUN dnf install -y socat
RUN dnf install -y findutils
RUN dnf install -y which
RUN dfn install -y cpio

